# Generated by Django 3.2.9 on 2022-02-15 20:11

import datetime
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_auto_20220215_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrequest',
            name='when',
            field=models.DateField(default=datetime.datetime.today, help_text='The date that this request was submitted', verbose_name='submitted when'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', help_text='The estimated cost of the item', max_digits=19, null=True, verbose_name='price (ea)'),
        ),
        migrations.AlterField(
            model_name='itemrequest',
            name='status',
            field=models.IntegerField(choices=[(1, '1) Under Consideration'), (2, '2) Approved'), (3, '3) Received'), (5, '5) Canceled or Denied')], default=1, help_text='The status of the request', verbose_name='Status'),
        ),
    ]
